const state={suggestion:0,format:'CSS',settings:{dark:false,email:true,autosave:true,ai:true}};
const formats=['CSS','React','Flutter','Figma','Lottie JSON'];
const code={
CSS:`.button {\n  background: #4F46E5;\n  transition: transform 300ms cubic-bezier(.34,1.56,.64,1);\n}\n.button:hover { transform: scale(1.06); }`,
React:`<motion.button\n  whileHover={{ scale: 1.06 }}\n  transition={{ type: "spring", duration: 0.3 }}\n>\n  Create Animation\n</motion.button>`,
Flutter:`AnimatedScale(\n  scale: isHovered ? 1.06 : 1.0,\n  duration: const Duration(milliseconds: 300),\n  curve: Curves.elasticOut,\n)`,
Figma:`Interaction: While hovering\nAnimation: Smart Animate\nDuration: 300ms\nEasing: Spring`,
'Lottie JSON':`{\n  "v": "5.7.0",\n  "fr": 60,\n  "ip": 0,\n  "op": 18,\n  "nm": "Spring Button Hover"\n}`};
function nav(){return `<header class="topbar"><div class="brand">AI Motion</div><nav class="nav"><button onclick="go('dashboard')">Dashboard</button><button onclick="go('create')">Create</button><button onclick="go('preview')">Preview</button><button onclick="go('export')">Export</button><button onclick="go('settings')">Settings</button></nav><button class="secondary" onclick="go('login')">Login</button></header>`}
function shell(content,title=''){return `${nav()}<main class="page">${content}</main><div class="footer">AI Micro-Interactions Customizer · AI-powered motion design workspace</div>`}
function landing(){return `<main class="page"><section class="hero"><span class="eyebrow">AI · Motion · Productivity</span><h1>AI Micro-Interactions Customizer</h1><p>Create physics-based, responsive micro-animations using natural language prompts.</p><div class="hero-actions"><button class="primary" onclick="go('login')">Start Designing</button><button class="secondary" onclick="go('dashboard')">Explore Dashboard</button></div></section><section class="feature-grid"><div class="card"><h3>Natural Language</h3><p class="muted">Describe the interaction you want in plain English.</p></div><div class="card"><h3>Physics-based Motion</h3><p class="muted">Tune spring, duration, speed and easing for responsive results.</p></div><div class="card"><h3>Export Anywhere</h3><p class="muted">Preview and export code for CSS, React, Flutter, Figma or Lottie.</p></div></section></main>`}
function login(){return shell(`<div class="screen-title"><h1>Login</h1><p>Sign in to continue to your AI motion workspace.</p></div><div class="card form-card"><div class="field"><label>Email</label><input id="email" type="email" placeholder="you@example.com"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="Enter password"></div><div class="row"><label class="check"><input type="checkbox"> Remember Me</label><button onclick="toast('Password reset link sent')" style="border:0;background:transparent;color:#4f46e5;font-weight:700">Forgot Password?</button></div><button class="primary" style="width:100%;margin-top:20px" onclick="loginGo()">Login</button><p style="text-align:center" class="muted">Don't have an account? <button onclick="toast('Demo account ready — use any email and password')" style="border:0;background:transparent;color:#4f46e5;font-weight:700;padding:0">Create New Account</button></p></div>`)}
function loginGo(){const email=document.getElementById('email')?.value.trim();const password=document.getElementById('password')?.value.trim();if(!email||!password){toast('Please enter email and password');return}toast('Login successful');setTimeout(()=>go('dashboard'),300)}
function dashboard(){return shell(`<div class="screen-title"><h1>Dashboard</h1><p>Welcome, User — manage your AI animation projects.</p></div><div class="dashboard-grid"><section class="card"><div class="row"><h3>Recent Projects</h3><button class="primary" onclick="go('create')">+ Create New Project</button></div><div class="projects"><button class="project" onclick="go('preview')"><span>Button Hover Animation</span><small class="muted">Edited today · Open</small></button><button class="project" onclick="go('preview')"><span>Login Success Animation</span><small class="muted">Edited yesterday · Open</small></button><button class="project" onclick="go('preview')"><span>Card Hover Effect</span><small class="muted">Edited 2 days ago · Open</small></button></div></section><aside class="card"><h3>Quick Actions</h3><div class="quick"><button class="secondary" onclick="go('create')">Generate Animation</button><button class="secondary" onclick="go('preview')">Preview</button><button class="secondary" onclick="go('export')">Export</button></div></aside></div>`)}
function create(){return shell(`<div class="screen-title"><h1>Create New Animation</h1><p>Describe the motion and let AI suggest responsive interactions.</p></div><div class="create-layout"><section class="card"><div class="field"><label>Project Name</label><input value="My Animation Project"></div><div class="field"><label>Platform</label><select><option>Web</option><option>React</option><option>Flutter</option><option>Figma</option></select></div><div class="field"><label>Animation Prompt</label><textarea rows="4">Create a smooth hover animation for a blue button with spring effect.</textarea></div><h3>Animation Settings</h3><div class="controls"><div class="control"><b>Duration</b><br><span class="muted">300 ms</span></div><div class="control"><b>Speed</b><br><span class="muted">Medium</span></div><div class="control"><b>Physics</b><br><span class="muted">Spring</span></div><div class="control"><b>Easing</b><br><span class="muted">Elastic</span></div></div><button class="primary" style="margin-top:20px" onclick="go('suggestions')">Generate Animation</button></section><aside class="card"><h3>AI Prompt Tips</h3><p class="muted">Mention the trigger, motion style, speed and desired feeling.</p><p><b>Example</b></p><p class="muted">“Make a button gently bounce on hover with a 300ms spring.”</p></aside></div>`)}
function suggestions(){return shell(`<div class="screen-title"><h1>AI Suggestions</h1><p>AI generated options based on your animation prompt.</p></div><div class="suggest-grid"><section>${[['Fade In','Spring','300 ms','Medium','100 ms'],['Spring Bounce','Spring','350 ms','Medium','0 ms'],['Elastic Pop','Elastic','280 ms','Fast','0 ms']].map((s,i)=>`<div class="suggestion ${state.suggestion===i?'selected':''}"><div><b>${s[0]}</b><div class="muted" style="margin-top:8px">Physics: ${s[1]} · Duration: ${s[2]} · Speed: ${s[3]} · Delay: ${s[4]}</div></div><button class="secondary" onclick="selectSuggestion(${i})">${state.suggestion===i?'Selected':'Apply'}</button></div>`).join('')}<button class="secondary" onclick="toast('New AI suggestions generated')">Regenerate</button></section><aside class="preview-shell"><div class="preview-toolbar"><i class="dot"></i><i class="dot"></i><i class="dot"></i></div><div class="preview-window"><button class="demo-btn">Animation Preview</button></div></aside></div>`)}
function selectSuggestion(i){state.suggestion=i;toast('Suggestion applied');render()}
function preview(){return shell(`<div class="screen-title"><h1>Live Preview</h1><p>Test your generated micro-interaction across responsive previews.</p></div><div class="card"><h3>Desktop Preview</h3><div class="preview-shell"><div class="preview-toolbar"><i class="dot"></i><i class="dot"></i><i class="dot"></i></div><div class="preview-window"><button class="demo-btn">Hover Me</button></div></div><div style="margin-top:18px"><h3>Mobile Preview</h3><div class="card" style="max-width:360px;margin:auto;display:grid;place-items:center;min-height:160px"><button class="demo-btn">Animation</button></div></div><div class="controls"><div class="control"><b>Duration</b><br><span class="muted">300 ms</span></div><div class="control"><b>Physics</b><br><span class="muted">Spring</span></div><div class="control"><b>Easing</b><br><span class="muted">Elastic</span></div><div class="control"><b>Iterations</b><br><span class="muted">1</span></div></div><div class="hero-actions" style="margin-top:20px"><button class="secondary" onclick="toast('Preview playing')">Play</button><button class="secondary" onclick="toast('Preview paused')">Pause</button><button class="secondary" onclick="toast('Preview restarted')">Restart</button><button class="primary" onclick="go('export')">Export</button></div></div>`)}
function exportPage(){return shell(`<div class="screen-title"><h1>Export Animation</h1><p>Choose a format and copy or download the generated implementation.</p></div><div class="export-grid"><section class="card"><h3>Choose Format</h3><div class="formats">${formats.map(f=>`<button class="format ${state.format===f?'active':''}" onclick="setFormat('${f}')">${f}</button>`).join('')}</div></section><section class="card"><h3>Generated Code Preview</h3><pre id="code">${escapeHtml(code[state.format])}</pre><div class="hero-actions" style="justify-content:flex-start;margin-top:16px"><button class="secondary" onclick="downloadCode()">Download</button><button class="secondary" onclick="copyCode()">Copy Code</button><button class="primary" onclick="toast('Export ready — file downloaded')">Export</button></div></section></div>`)}
function setFormat(f){state.format=f;render()}
async function copyCode(){try{await navigator.clipboard.writeText(code[state.format]);toast('Code copied to clipboard')}catch(e){toast('Select and copy the code manually')}}
function downloadCode(){const ext=state.format==='CSS'?'css':state.format==='React'?'jsx':state.format==='Flutter'?'dart':state.format==='Figma'?'txt':'json';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([code[state.format]],{type:'text/plain'}));a.download='ai-motion-animation.'+ext;a.click();toast('Code file downloaded')}
function settings(){return shell(`<div class="screen-title"><h1>Settings</h1><p>Manage your profile and animation workspace preferences.</p></div><div class="card" style="max-width:760px;margin:auto"><h3>Profile Information</h3><div class="card" style="box-shadow:none;background:#f8fafc;margin:15px 0 20px"><p><b>Name:</b> Jarin Sreya</p><p><b>Email:</b> jarin@example.com</p><p><b>Role:</b> Designer</p></div><div class="settings-list">${[['dark','Dark Mode'],['email','Email Notifications'],['autosave','Auto Save Projects'],['ai','Enable AI Suggestions']].map(([k,t])=>`<div class="setting"><span>${t}</span><button class="switch ${state.settings[k]?'on':''}" onclick="toggleSetting('${k}')"><i></i></button></div>`).join('')}</div><div class="field" style="max-width:220px;margin-top:24px"><label>Language</label><select><option>English</option><option>বাংলা</option></select></div><button class="primary" onclick="toast('Settings saved')">Save Changes</button><button class="secondary" style="margin-left:8px" onclick="go('landing')">Logout</button></div>`)}
function toggleSetting(k){state.settings[k]=!state.settings[k];render()}
function escapeHtml(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),1800)}
function go(route){location.hash=route;render()}
function render(){const r=location.hash.slice(1)||'landing';let html=r==='landing'?landing():r==='login'?login():r==='dashboard'?dashboard():r==='create'?create():r==='suggestions'?suggestions():r==='preview'?preview():r==='export'?exportPage():r==='settings'?settings():landing();document.getElementById('app').innerHTML=html}
window.addEventListener('hashchange',render);render();
